Коннектор к UCP.
cusodede/ppl pull request #104
Opened 2021-08-12 13:51 UTC by Fullchaos

Получение данных об абоненте из UCP и запрос баланса.

2021-08-12 20:07 UTC, pozitronik requested changes

2021-08-12 20:07 UTC, pozitronik commented on modules/api/connectors/ucp/UcpConnector.php
> +	private string $authService;
Отсутствует default-инициализация у переменных класса, не инициализируемых в конструкторе. Класс упадёт при создании.

2021-08-13 06:58 UTC, pozitronik approved these changes

2021-08-13 07:09 UTC, alxlapin requested changes

2021-08-13 07:09 UTC, alxlapin commented on modules/api/connectors/ucp/UcpConnector.php
> +		$this->setAuthToken($this->getToken());
Это лишнее, getToken работает через кэш, поэтому доп. прослойка не нужна

2021-08-13 07:09 UTC, alxlapin commented on modules/api/connectors/ucp/UcpConnector.php
> +						. http_build_query(['sys' => 'bauth', 'login' => $this->login, 'password' => $this->password])
1. $this->getClient()->post(), абстракции уже предусмотрены
2. http_build_query лишнее, метод post принимает url в привычном для Yii формате, в виде массива

2021-08-13 07:09 UTC, alxlapin commented on modules/api/connectors/ucp/UcpConnector.php
> +			->setMethod('get')
same, $this->getClient()->get()

2021-08-13 08:04 UTC, alxlapin approved these changes

2021-08-13 08:05 UTC, merged