Controller refactor
cusodede/ppl pull request #17
Opened 2021-05-24 07:14 UTC by alxlapin

Убрал всё лишнее из контроллеров, наследуемое от базового класса

2021-05-24 07:17 UTC, Fullchaos approved these changes

2021-05-25 04:15 UTC, pozitronik requested changes
Ты поменял форматирование кода, уходящего в апстрим и оттуда в dpl.
И там и там копятся изменения, которые мне необходимо будет мержить. И это ровно то, о чём я говорил: разница в форматировании очень затрудняет мерж.
В данном случае, конечно, я могу всё исправить сам, но хотел бы, чтоб на будущее это учитывалось. Код своего проекта форматируй, как удобно тебе, но то, что ходит туда-сюда в апстрим, форматируй, как там.

А лучше всего было бы сделать изменения, относящиеся к апстриму в его же репозитории.

2021-05-25 04:15 UTC, pozitronik commented on controllers/UsersController.php
>  	public function actionLogoGet(int $id = null): void
Неправильная типизация.

2021-05-25 10:48 UTC, alxlapin commented on controllers/UsersController.php
>  	public function actionLogoGet(int $id = null): void
Ты про ?int  ?

2021-05-25 11:26 UTC, Fullchaos commented
Леха, влей мастер там еще раздел подписок, есть. И да, я бы вносил изменения в апстрим в соответствующей репе, так всем будет удобнее.

2021-05-25 11:42 UTC, pozitronik commented on controllers/UsersController.php
>  	public function actionLogoGet(int $id = null): void
Я про ?int

2021-05-25 14:06 UTC, alxlapin commented
@pozitronik  Паш, ты по итогу в этот раз переформатируешь сам? На будущее учту, понятнео дело.

2021-05-25 18:54 UTC, pozitronik commented
Да, я сам всё перепишу прямо в bc.

2021-05-26 10:49 UTC, pozitronik commented
Перенёс изменения в bc.

2021-05-26 10:49 UTC, closed without merging