PRPL-10_partner-api-connectors
cusodede/ppl pull request #20
Opened 2021-05-24 13:54 UTC by alxlapin

Для обсуждения: примерная структура коннекторов для общения с внешними API на примере IVI и VetExpert

2021-05-25 04:31 UTC, pozitronik commented on migrations/m210524_091058_add_db_cache_table.php
> +<?php
Ты делаешь одну задачу (коннекторы) и в ней создаёшь таблицу кеша, что, очевидно, задача левая. Вынеси в отдельную ветку.

2021-05-25 04:32 UTC, pozitronik commented on modules/api/connectors/BaseHttpConnector.php
> +	public function __construct(array $clientOptions = [], array $config = [])
![изображение](https://user-images.githubusercontent.com/2357892/119439593-5effd500-bd2b-11eb-9385-b33415413317.png)

2021-05-25 04:33 UTC, pozitronik commented on modules/api/connectors/vetexpert/CallbackParams.php
> +	public function setPhone(string $phone): void
PHPDoc?

2021-05-25 04:37 UTC, pozitronik commented on modules/api/connectors/vetexpert/CallbackParams.php
> +	#[ArrayShape(["phone" => "string", "email" => "string", "first_name" => "string", "last_name" => "string", "middle_name" => "string", "subscription_to" => "string"])]
Мы пока не перешли на 8.0.

2021-05-25 04:38 UTC, pozitronik commented on modules/api/connectors/vetexpert/CallbackParams.php
> +	public function setSubscriptionTo(\DateTime $date): void
Вызываем через use DateTime
Без FQN.

2021-05-25 04:39 UTC, pozitronik commented on modules/api/connectors/vetexpert/VetExpertConnector.php
> +		return Yii::$app->dbCache->getOrSet(
Почему именно dbCache? Другие кеши не годятся?

2021-05-25 04:41 UTC, pozitronik requested changes
Смотри комментарии

2021-05-25 06:24 UTC, alxlapin commented on modules/api/connectors/vetexpert/CallbackParams.php
> +	public function setSubscriptionTo(\DateTime $date): void
В таком случае, надо бы инспекцию соответствующую подрубить (если быть точнее, опции внутри инспекции). А то сейчас не ругается

2021-05-25 06:27 UTC, pozitronik commented on modules/api/connectors/vetexpert/CallbackParams.php
> +	public function setSubscriptionTo(\DateTime $date): void
> 
> 
> В таком случае, надо бы инспекцию соответствующую подрубить (если быть точнее, опции внутри инспекции). А то сейчас не ругается

Шторм почему-то не ругается на подключение внутренних классов через \. Я не разбирался, почему, просто привык уже подчищать.

2021-05-25 06:31 UTC, alxlapin commented on modules/api/connectors/vetexpert/VetExpertConnector.php
> +		return Yii::$app->dbCache->getOrSet(
Исходил из постановки задачи. Например, Ivi дает ключ с неограниченным сроком жизни, и хотелось этот ключ изолировать его максимально. В случае с VetExpert время жизни ключа 15 минут, файловый кеш я всерьез на рассматриваю, поэтому в качестве основного использовал бы redis. DbCache нам понадобится на сейчас, так потом, поэтому в отдельную ветку я это вынесу

2021-05-25 06:32 UTC, alxlapin commented on modules/api/connectors/vetexpert/CallbackParams.php
> +	public function setPhone(string $phone): void
Будет, я пока продвигаю идеи, шашечки будут позже :)

2021-05-25 06:40 UTC, pozitronik commented on modules/api/connectors/vetexpert/VetExpertConnector.php
> +		return Yii::$app->dbCache->getOrSet(
С точки зрения приложения, все кеши одинаковые, у нас есть единый интерфейс, а реализацию выбираем в конфигурации. Нас не должно заботить, через что настроен кеш, более того - указывать определённый кеш, который может отличаться от системного - плохая идея.

2021-05-25 06:45 UTC, alxlapin commented on modules/api/connectors/vetexpert/CallbackParams.php
> +	public function setSubscriptionTo(\DateTime $date): void
![Screenshot from 2021-05-25 09-41-52](https://user-images.githubusercontent.com/15965193/119451389-db9baf00-bd3d-11eb-954e-bdd43c66cbc2.png)

2021-05-25 06:49 UTC, alxlapin commented on modules/api/connectors/vetexpert/VetExpertConnector.php
> +		return Yii::$app->dbCache->getOrSet(
Ты предлагаешь использовать единый кеш под все задачи?

2021-05-25 07:04 UTC, artemvolt commented on modules/api/connectors/vetexpert/VetExpertConnector.php
> +		return Yii::$app->dbCache->getOrSet(
Скорей всего, Паша имеет ввиду, что ты можешь в конструктор выставить CacheInterface и в методе ссылаться через $this->cache, а какой конкретно Кеш кидать - сетить через конфиг или при ручном создании.
@pozitronik ?

2021-05-25 07:12 UTC, pozitronik commented on modules/api/connectors/vetexpert/CallbackParams.php
> +	public function setSubscriptionTo(\DateTime $date): void
Точно! Эту-то галочку я и искал!

2021-05-25 07:15 UTC, pozitronik commented on modules/api/connectors/vetexpert/CallbackParams.php
> +	public function setSubscriptionTo(\DateTime $date): void
Пушнул в 751485e3ee74fae1e6b4bbfd63815f532b6253f2

2021-06-01 11:29 UTC, alxlapin commented
TODO:

- [ ] предусмотреть дополнительную валидацию JWT по параметрам внутри payload строки (claims validation)
- [ ] предусмотреть поле для типа токена в таблице sys_users_tokens
- [ ] рассмотреть использование sys_users_tokens для нужд хранения refresh token'а. Сейчас токен сохраняется в таблице sys_users (restore_code), без возможности задания времени жизни

2021-06-01 12:10 UTC, Fullchaos approved these changes

2021-06-01 12:52 UTC, Fullchaos approved these changes

2021-06-07 11:25 UTC, closed without merging

2021-06-07 11:26 UTC, alxlapin commented
Где кнопка "удалить ПР"?! М, м?!