Prpl 12 subscriptions journal
cusodede/ppl pull request #25
Opened 2021-06-04 11:16 UTC by Fullchaos

2021-06-05 07:22 UTC, pozitronik requested changes

2021-06-05 07:22 UTC, pozitronik commented on controllers/SubscriptionsController.php
> +			$subscription->link('product', $product); // Цепляем к партнеру и сохраняем
Это не будет работать, поскольку до связывания $subscription у тебя не сохранено в БД.
Я бы вообще сделал немного по другому: сделал бы link() в сеттере свойства с проверкой на isNewRecord() и "переносом" link(), в таком случае, на событие ActiveRecord::EVENT_AFTER_INSERT.

2021-06-05 07:22 UTC, pozitronik commented on controllers/SubscriptionsController.php
> +		// Иключаем produc_id из валидации
![изображение](https://user-images.githubusercontent.com/2357892/120883798-e250de80-c5e7-11eb-8c44-8622e01019c9.png)
Не забывай инспектировать.

2021-06-05 10:04 UTC, Fullchaos commented on controllers/SubscriptionsController.php
> +			$subscription->link('product', $product); // Цепляем к партнеру и сохраняем
Это не совсем так. Не работало бы, если я бы не сохранил $product, а link делает связь и сохраняет, все работает, проверь.

2021-06-05 10:07 UTC, Fullchaos commented on controllers/SubscriptionsController.php
> +		// Иключаем produc_id из валидации
Почему то не срабатывают инспекции.
<img width="346" alt="Снимок экрана 2021-06-05 в 13 05 27" src="https://user-images.githubusercontent.com/41751396/120888042-e9cfb200-c5fe-11eb-978d-762303d72e76.png">

2021-06-05 10:16 UTC, Fullchaos commented on controllers/SubscriptionsController.php
> +		// Иключаем produc_id из валидации
Ошибки поправил, ненужные импорты удалил.

2021-06-05 10:26 UTC, pozitronik commented on controllers/SubscriptionsController.php
> +			$subscription->link('product', $product); // Цепляем к партнеру и сохраняем
Да, верно, link() сохраняет модель при связи 1:1, я не туда посмотрел. Как-то это неочвеидно, но ок.

2021-06-07 10:30 UTC, artemvolt commented on controllers/SubscriptionsController.php
> +			$product->type_id = RefProductsTypes::ID_SUBSCRIPTION; // Определяем, что это подписка
Лучше инкапсулировать логику, например, создать метод ->subscription() : void.
Данными манипулирует тот класс, который ими владеет. Проще будет потом изменять, расширять поведение.

2021-06-07 10:32 UTC, artemvolt commented on controllers/SubscriptionsController.php
> +			$product->save();
Лучше обработать ошибку, если сохранения не произойдет. Если, конечно, это требуется.

2021-06-07 10:39 UTC, artemvolt commented on controllers/SubscriptionsController.php
> +			$subscription->link('product', $product); // Цепляем к партнеру и сохраняем
я так понял работает связка двух сущностей, мб надо обернуть в транзакцию?

2021-06-07 10:40 UTC, artemvolt commented on controllers/SubscriptionsController.php
> +			$subscription->link('product', $product); // Цепляем к партнеру и сохраняем
аналогично про транзакцию

2021-06-07 10:41 UTC, Fullchaos commented on controllers/SubscriptionsController.php
> +			$subscription->link('product', $product); // Цепляем к партнеру и сохраняем
Как мы узнаем product_id?

2021-06-08 16:24 UTC, pozitronik approved these changes

2021-06-08 16:24 UTC, merged