Api connector vetexpert
cusodede/ppl pull request #29
Opened 2021-06-08 10:41 UTC by alxlapin

First at all #28 

Добавлена обвязка под АПИ VetExpert'а

2021-06-08 13:05 UTC, pozitronik requested changes

2021-06-08 13:05 UTC, pozitronik commented on modules/api/connectors/vet_expert/CallbackParams.php
> +		$this->_phone = str_replace('+', '', Phones::defaultFormat($this->_phone));
В апстриме добавился метод nationalFormat(), думаю, он тебе нужен. Если нет, то посмотри библиотеку, там есть способы получения любого нужного формата номера.

2021-06-08 13:05 UTC, pozitronik commented on modules/api/connectors/vet_expert/CallbackParams.php
> +		/** @noinspection PhpFieldAssignmentTypeMismatchInspection */
Не глуши.

2021-06-08 13:05 UTC, pozitronik commented on modules/api/connectors/vet_expert/VetExpertConnector.php
> +	 * @noinspection PhpFieldAssignmentTypeMismatchInspection
😞

2021-06-15 09:20 UTC, artemvolt commented on modules/api/connectors/vet_expert/VetExpertConnector.php
> +				return $response->data['token'] ?? null;
Может стоит сделать проверку на success ответа?
Если каким-то чудом, token не будет присутствовать в data, у тебя закешируется null.

2021-06-15 09:34 UTC, artemvolt commented on modules/api/connectors/vet_expert/VetExpertConnector.php
> +	public function callback(CallbackParams $params, string &$error): bool
Я бы не стал менять внешнюю переменную  $error, мало ли, это станет массивом?  Лучше изменять внутри и возвращать наружу измененную - проще дебажить, в случае чего.
Если тебе надо собирать массив ошибок, кинь в методе exception и его лови снаружи.

Размышления:
Метод называется callback, но возвращает bool. 
Мб стоит возвращать response оригинальный и завести два отдельных метода: createSubscribe, updateSubscribe или один, и в нем уже дергать callback? Ну тип так проще будет потом искать методы и более понятно, что мы можем на текущий момент получить у ветэксперта.

2021-06-15 09:34 UTC, artemvolt approved these changes

2021-06-15 14:36 UTC, artemvolt approved these changes

2021-06-16 10:44 UTC, pozitronik approved these changes

2021-06-16 10:46 UTC, Fullchaos approved these changes

2021-06-16 10:47 UTC, merged