Базовые сущности Партнеров, Типов, Продуктов
cusodede/ppl pull request #3
Opened 2021-05-13 15:11 UTC by Fullchaos

!Ошибка unknown property value при сохранении модели в справочнике

2021-05-13 15:23 UTC, alxlapin commented on migrations/m210513_113311_products.php
> +		$this->createIndex('idx-products-user_id', 'products', 'user_id');
Лёха, для внешних ключей индексы создаются автоматом

2021-05-13 15:25 UTC, alxlapin commented on migrations/m210513_112805_partners.php
> +		$this->createIndex('idx-partners-deleted', 'partners', 'deleted');
Предлагаю пока не ставить индексы с опережением - посмотрим на объемы данных и динамику использования данного поля

2021-05-13 18:08 UTC, Fullchaos commented on migrations/m210513_112805_partners.php
> +		$this->createIndex('idx-partners-deleted', 'partners', 'deleted');
Спорно... Зачем потом накидывать на живые данные, когда можно сразу? Да и место он не займет много.

2021-05-13 18:30 UTC, Fullchaos commented on migrations/m210513_113311_products.php
> +		$this->createIndex('idx-products-user_id', 'products', 'user_id');
Принял, поправил миграцию.

2021-05-14 08:09 UTC, pozitronik commented
Не нужно разделять RefProductsTypes на Reference и ActiveRecord-модели. Reference наследуется от ActiveRecord, не стоит дразнить Оккама.

2021-05-14 08:18 UTC, pozitronik requested changes
Не нужно разделять RefProductsTypes на Reference и ActiveRecord-модели. Reference наследуется от ActiveRecord, не стоит дразнить Оккама.
Исправь и можно вливать.

2021-05-14 09:07 UTC, pozitronik approved these changes

2021-05-14 09:07 UTC, merged