Mobile api
cusodede/ppl pull request #37
Opened 2021-06-17 13:57 UTC by alxlapin

2021-06-17 14:07 UTC, alxlapin commented on models/abonents/RelAbonentsToProducts.php
> +		return $this->hasMany(ProductStatuses::class, ['rel_abonents_to_products_id' => 'id']);
@pozitronik Это то, о чем я говорил в чате. Я переопределяю релейшн с той целью, чтобы использовался корректный ProductStatuses, а не active_record\ProductStatuses. 
Ну и по всем остальным релейшенам та же суть.

2021-06-17 16:14 UTC, Fullchaos approved these changes
Есть общее пожелание: больше комментариев, описание классов, неочевидных методов ...

2021-06-18 10:12 UTC, artemvolt approved these changes

2021-06-18 10:14 UTC, artemvolt commented on modules/api/mobile_api/resources/ProductsResource.php
> +		$abonentModel = Abonents::find()
c 22 по 33 строку ты можешь вынести это в метод getByPhone в AbonentsSearchModel,  как вариант.

2021-06-19 18:03 UTC, pozitronik requested changes

2021-06-19 18:03 UTC, pozitronik commented on models/products/EnumProductsStatuses.php
> +<?php
Для инфо: у нас будет модель [ArrayReference](https://github.com/cusodede/dpl/commit/e9a97a078aafb1f93c9ba68c7785e132b362b00d), с которой можно будет работать, как с любым справочником.

2021-06-20 19:42 UTC, alxlapin commented on helpers/DateHelper.php
> +use pozitronik\helpers\DateHelper as VendorDateHelper;
@pozitronik а зачем это в помойке? Область применения четко обозначена, хоть бери и в апстрим сливай. Каждый раз дорабатывать вендорный пакет замороченно, поэтому вынес в проектную область видимости.

2021-06-20 19:43 UTC, alxlapin commented on models/products/EnumProductsStatuses.php
> +<?php
@pozitronik конкретно в данном кейсе что мне это даёт?

2021-06-20 20:01 UTC, pozitronik commented on models/products/EnumProductsStatuses.php
> +<?php
Про конкретный случай не знаю, но помню, что речь о "псевдо-enum" пошла после того, как попытались вместо них юзать справочники.
Ну вот, будут справочники из массивов, только на чтение. Может пригодится.

2021-06-20 20:13 UTC, pozitronik commented on helpers/DateHelper.php
> +use pozitronik\helpers\DateHelper as VendorDateHelper;
Я твою мысль понимаю. Тогда мож сделаешь pr в yii2-helpers?

2021-06-23 15:40 UTC, Fullchaos approved these changes

2021-06-23 16:45 UTC, pozitronik approved these changes

2021-06-24 09:32 UTC, merged