Интерфейсы журналирования подключений и списаний
cusodede/ppl pull request #58
Opened 2021-07-01 13:08 UTC by alxlapin

2021-07-02 12:45 UTC, Fullchaos approved these changes

2021-07-02 21:22 UTC, pozitronik requested changes
Нужно влить master, порешав конфликты. Я не могу этого сделать, поскольку не отслеживаю все изменения.
После слияния нужно исправить все замечания инспекций.
Изменения в ModalHelper я пропущу, но нужно будет создать тикет со ссылкой на изменение, чтобы не забыть перенести их в апстрим.

2021-07-02 21:22 UTC, pozitronik commented on assets/assets/modalHelper/js/modalHelper.js
> -		$('#' + modalDivId).modal('show');
Хелпер общий для всех приложений. Вносишь изменения - вноси в апстрим, чтобы он и дальше таким оставался.
Что пытался сделать - мне понятно, но стоило бы посоветоваться.

2021-07-06 06:59 UTC, alxlapin commented
https://github.com/cusodede/bc/issues/40

2021-07-06 14:36 UTC, Fullchaos approved these changes

2021-07-06 19:58 UTC, pozitronik commented on modules/api/connectors/vet_expert/SubscriptionParams.php
> +	 * @noinspection ParameterDefaultValueIsNotNullInspection
1. Заглушенная инспекция в большей части случаев означает "я не понял, в чём дело". Имеет смысл поинтересоваться в чате.
2. Если ты действительно уверен, что срабатывание ложно-положительное - в комментарии опиши, почему (если это не 100% очевидно, или не тудуха - последнее маркируется через todo).
3. Данная инспекция отсутствует в профиле Quick, есть только в Full. Я не прошу у вас прохождения Full, там включены проверки, которые с одной стороны, часто дают ложно-положительные срабатывания, а с другой - позволяют выявить реальные архитектурные недочёты. Но над каждым срабатыванием надо задумываться. Заглушив инспекцию, ты спрятал кусок кода от дальнейшего анализа.

В общем, так делать не стоит.

Что касается непосредственно этого срабатывания: [вот полное и исчерпывающее описание](https://github.com/kalessil/phpinspectionsea/blob/master/docs/code-style.md#non-null-default-value-parameters), я даже не знаю, что к нему добавить.

2021-07-06 20:14 UTC, pozitronik approved these changes

2021-07-06 20:15 UTC, merged