Создание, редактирование партнера. Поисковые модели, миграции, контро…
cusodede/ppl pull request #6
Opened 2021-05-17 14:42 UTC by Fullchaos

Переименовал конфиги в .php

2021-05-17 20:19 UTC, pozitronik commented on controllers/PartnersController.php
> +		if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
1) Здесь не будет сохранения постинга, пришедшего в AJAX.

2021-05-17 20:21 UTC, pozitronik commented on controllers/PartnersController.php
> +		return $model->createModelFromPost() ? $this->redirect('index') : $this->renderAjax('modal/create', compact('model'));
Эм... Экшен предназначен ТОЛЬКО для ajax?
Почему не сделать, как в остальном проекте - разруливать в зависимости от Yii::$app->request->isAjax?

2021-05-17 20:21 UTC, pozitronik commented on controllers/PartnersController.php
> +	public function actionEdit(int $id)
Те же вопросы, что к actionCreate()

2021-05-17 20:27 UTC, pozitronik commented on views/layouts/subviews/sidebar.php
> +			'label' => 'Парнтнеры',
Поставь Grazie, плагин для проверки правописания. Он будет использоваться при проектных инспекциях, если ты их прогонял, конечно.

2021-05-17 20:31 UTC, pozitronik requested changes
@Fullchaos, завтра проговорим логику контроллера. Возможно, ты не очень понял, что я заложил в систему.

2021-05-17 21:39 UTC, Fullchaos commented on controllers/PartnersController.php
> +		if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
Уникальность ИНН партнера, можно проверить только на стороне сервера. Чтобы не перегружать форму, можно сделать ajax валидацию ActiveForm::validate($model). Если есть ошибки (есть такой ИНН) отдать их в json.

2021-05-17 21:48 UTC, Fullchaos commented on views/layouts/subviews/sidebar.php
> +			'label' => 'Парнтнеры',
Поставил, давно но в tools не могу его найти. Опечатку исправил.

2021-05-18 17:51 UTC, pozitronik approved these changes

2021-05-19 07:06 UTC, merged